

on:
  push:

jobs:
#  test:
#    uses: ./.github/workflows/test.yml
  cd:
#    needs: [test]
    if: github.ref == 'refs/heads/dev'
    strategy:
      matrix:
        conf:
          - name: tasq-back
            dockerFile: Dockerfile
            manifestFile: ./tasq/back/backend.yml
            repository: as-wasabi/k8s-wasabi
    runs-on: ubuntu-latest
    env:
      harborUser: robot$wasabi
      dir: "./"
    steps:
      # checkout
      - uses: actions/checkout@v4
      - name: preBuild
        if: ${{ matrix.conf.preDockerBuildCmd }}
        run: ${{ matrix.conf.preDockerBuildCmd }}

      # docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: harbor.kigawa.net
          username: ${{ env.harborUser }}
          password: ${{ secrets.HARBOR_PASS }}

      - uses: docker/build-push-action@v5
        with:
          context: ${{ env.dir }}
          file: ${{ matrix.conf.dockerFile }}
          push: true
          tags: harbor.kigawa.net/private/${{ matrix.conf.name }}:${{ github.ref_name }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ env.dockerArg }}


      # argo
      - name: checkout manifest repository
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.conf.repository }}
          ref: main
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update YAML File
        run: |
          yq -i '.spec.template.spec.containers[0].image = "harbor.kigawa.net/private/${{ matrix.conf.name }}:${{ github.ref_name }}-${{ github.sha }}"' \
          ${{ matrix.conf.manifestFile }}

      - name: push
        run: |
          git config user.name githubActions
          git config user.email bot@kigawa.net
          git add .
          git commit --author=. -m "update rev"
          git push
